#!/usr/bin/env bash

set -ueo pipefail

info() {
    printf "%s\n" "$*" >&2
}
error() {
    printf "\e[31m%s\e[m\n" "$*" >&2
}

root="${GIST_ROOT:-}"
if [[ -z "$root" ]]; then
    error '$GIST_ROOT is not set'
    exit 1
fi
root="$(realpath "$root")"

create_one() {
    local name="$1"
    local now="$2"
    local dir="$root/$name"
    if [[ -d "$dir" ]]; then
        error "Gist '$name' already exists"
        return 1
    fi

    local gist_json="$dir/.gist.json"
    local workspace="$dir/$name.code-workspace"
    mkdir -p "$dir"
    [ -f "$gist_json" ] || printf '{"created_at": "%s"}\n' "$now" > "$gist_json"
    [ -f "$workspace" ] || printf '{\n  "folders": [\n    {\n      "path": "."\n    }\n  ]\n}\n' > "$workspace"

    info "Gist '$name' created"
}

create() {
    local now
    now="$(date --iso-8601=seconds)"
    for name in "$@"; do
        create_one "$name" "$now"
    done
}

list() {
    local find_cmd
    if fd --version &>/dev/null; then
        find_cmd=(fd --type f --hidden --follow --glob .gist.json "$root")
    else
        find_cmd=(find "$root" -type f -name .gist.json)
    fi
    "${find_cmd[@]}" | while read -r file; do
        local dir="${file%/.gist.json}"
        local name="${dir##*/}"
        if jq -e '.archived_at' "$file" &>/dev/null; then
            continue
        fi
        if ! jq -e '.created_at' "$file" &>/dev/null; then
            continue
        fi
        local created_at
        created_at="$(jq -r '.created_at' "$file" 2>/dev/null | sed 's/T/\t/g')"
        printf '%s\t%s\n' "$created_at" "$name"
    done | sort --reverse | awk -F'\t' '{printf "%s / %s\n", $1, $3}'
}

archive_one() {
    local name="$1"
    local dir="$root/$name"
    local gist_json="$dir/.gist.json"
    if [ ! -f "$gist_json" ]; then
        error "Gist '$name' does not exist"
        return 1
    fi
    local now
    now="$(date --iso-8601=seconds)"
    jq --arg archived_at "$now" '. + {archived_at: $archived_at}' "$gist_json" > "$gist_json.tmp" && mv "$gist_json.tmp" "$gist_json"
    info "Gist '$name' archived"
}

archive() {
    for name in "$@"; do
        archive_one "$name"
    done
}

unarchive_one() {
    local name="$1"
    local dir="$root/$name"
    local gist_json="$dir/.gist.json"
    if [ ! -f "$gist_json" ]; then
        error "Gist '$name' does not exist"
        return 1
    fi
    jq 'del(.archived_at)' "$gist_json" > "$gist_json.tmp" && mv "$gist_json.tmp" "$gist_json"
    info "Gist '$name' unarchived"
}

unarchive() {
    for name in "$@"; do
        unarchive_one "$name"
    done
}

prog="${0##*/}"

case "${1:-}" in
    --version)
        printf '%s\n' "0.0.1"
        ;;
    root)
        printf '%s\n' "$root"
        ;;
    create)
        shift
        create "$@"
        ;;
    list)
        shift
        list "$@"
        ;;
    archive)
        shift
        archive "$@"
        ;;
    unarchive)
        shift
        unarchive "$@"
        ;;
    *)
        error "usage: $prog (create|list|archive|unarchive) ..."
        exit 1
        ;;
esac
